name: Swift

on:
  push:
    branches: [ gh-wf ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v1.1
      with:
        project: MeetingBar.xcodeproj
        scheme: MeetingBar
        action: build

